name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/reusable_build.yaml

  deploy:
    needs: build      # waits for build to pass first
    uses: ./.github/workflows/reusable_deploy.yaml
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
